config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'

  get 'tasks', to: redirect('/'), as: :tasks

  resources :tasks, except: :index do
    member do
      get 'mark_as_performed', as: :mark_as_performed
    end
  end

  scope :sms_notifications do
    post 'smsru_callback', to: 'sms_notifications#smsru_callback'
  end

  devise_for :users, sign_out_via: [:get, :delete]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  require 'sidekiq/web'
  authenticated :admin_user do
    scope "/sidekiq" do
      mount Sidekiq::Web => '/'
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/sms_notification.rb
class SmsNotification < ActiveRecord::Base
  enum status: [ :need_send, :canceled, :delivered, :error_on_deliver, :sent]
  belongs_to :task
  before_create :set_delivery_date
  after_create :create_job

  def phone
    task.user.phone
  end

  def message_text
    "You need perform #{task.name}"
  end

  private

  def set_delivery_date
    self.delivery_date = task.start_date
  end

  def create_job
    logger.debug("[SMS] Create job for SmsNotification\##{id} #{delivery_date}")
    SendSmsJob.set(wait_until: task.start_date).perform_later(sms_notification_id: id)
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  enum status: [ :not_performed, :performed ]
  belongs_to :user, dependent: :destroy
  has_one :sms_notification
  
  after_initialize :set_default_start_date

  scope :already_need_perform, -> { not_performed.where('start_date <= ?', Time.now) }

  scope :in_future, -> { not_performed.where('start_date > ?', Time.now) }

  before_update :update_sms_notification

  def mark_as_performed
    return self.status = :performed if repeat_count == 0
    
    self.repeat_count -= 1
    self.start_date = next_start_date
  end

  def save_as_performed
    mark_as_performed
    save
  end

  def next_start_date
    start_date + every_minutes.minutes + every_hours.hours + every_days.days + every_months.months + every_years.years
  end

  def repeating
    every_attributes = attributes.select {|k, v| (k =~ /^every/) && (v > 0)}

    every_attributes.empty? ? I18n.t("tasks.repeating.none") : repeating_text(every_attributes)
  end

  def repeatable?
    repeat_count > 0
  end

  def notify_by_sms
    sms_notification.present?
  end

  def sms_delivered?
    sms_notification.delivered?
  end

  private

  def set_default_start_date
    start_date ||= Time.now
  end

  def repeating_text(attributes)
    attributes_as_string = attributes.map { |k,v| "#{v} #{I18n.t(k, scope:'tasks.form')}"}.join(', ')
    "#{I18n.t('tasks.repeating.every')} #{attributes_as_string}"
  end

  def update_sms_notification
    if sms_notification.present? && sms_notification.delivery_date != start_date
      sms_notification.delete
      create_sms_notification 
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :phone]
  end


  def set_locale
    locale = params[:locale]
    
    if locale.blank? 
      I18n.locale = session[:locale] || I18n.default_locale
      return
    end

    if I18n.available_locales.map(&:to_s).include?(locale)
      I18n.locale = locale
      session[:locale] = locale
      logger.error("set locale to #{locale}")
    else
      flash.now[:notice] = "#{locale} translation not available"
    end
  end
end

app/controllers/sms_notifications_controller.rb
class SmsNotificationsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :smsru_callback
  skip_before_action :authenticate_user!,  only: :smsru_callback

  layout false

  def smsru_callback
    parsed_params = smsru_callback_params
      
    if parsed_params.empty?
      logger.error "[SMS] Received bad callback params."
      return render(text: '100')
    end

    if parsed_params[:code] == 103
      sms = SmsNotification.where(sms_id: parsed_params[:sms_id]).last
      sms.status = :delivered
      sms.save

      logger.debug("[SMS] Sms notification \##{s.id} delivered")
    else
      logger.error('[SMS] Callback return status != 103')
    end

    render text: '100'
  end

  private

  def smsru_callback_params
    begin
      permited = params.require(:data).permit('0')
      splited_params = permited['0'].split("\n")
      if splited_params[0] == 'sms_status' 
        {
          method: splited_params[0],
          sms_id: splited_params[1],
          code: splited_params[2].to_i
        }
      else
        {}
      end
    rescue ActionController::ParameterMissing  
      {}
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, except: [:new, :index, :create]

  def index
    @already_need_perform = current_user.tasks.already_need_perform.order(start_date: :asc)
    @in_future = current_user.tasks.in_future.order(start_date: :asc)
    @performed_tasks = current_user.tasks.where(status: 1).order(start_date: :desc)
  end

  def new
    @task = Task.new(start_date: Time.now + 1.hour)
  end

  def create
    task = current_user.tasks.create(task_params)

    task.create_sms_notification if params[:task][:notify_by_sms]

    redirect_to root_path
  end

  def edit
  end

  def update
    @task.sms_notification.delete unless params[:task][:notify_by_sms]

    @task.update(task_params)
    
    redirect_to root_path
  end

  def destroy
    @task.destroy()
    redirect_to root_path
  end

  def mark_as_performed
    @task.save_as_performed
    redirect_to :back
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :start_date, :repeat_count, 
      :every_minutes, :every_hours, :every_days, :every_months, :every_years)
  end
end

app/views/admin/tasks/_repeating_form.html.slim
li.every
  .title = "#{t('tasks.repeating.repeat')} #{t('tasks.repeating.every')}"
  = fields_for :task do |task_fields|
    = task_fields.number_field :every_minutes, min: 0
    = label_tag :every_minutes, t('tasks.form.every_minutes')

    = task_fields.number_field :every_hours, min: 0
    = label_tag :every_hours, t('tasks.form..every_hours')

    = task_fields.number_field :every_days, min: 0
    = label_tag :every_days, t('tasks.form..every_days')

    = task_fields.number_field :every_months, min: 0
    = label_tag :every_months, t('tasks.form.every_months')

    = task_fields.number_field :every_years, min: 0
    = label_tag :every_years, t('tasks.form.every_years')

app/views/layouts/application.html.slim
doctype html
html
  head
    title TasksNotifications
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'shared/navbar'
    .container
      = render 'shared/flash'
      - if yield(:title).present?
        .page-header
          .h1
            = yield :title
      = yield

app/views/shared/_flash.html.slim
- if alert
  .alert.alert-warning.alert-dismissable
    button.close aria-hidden="true" data-dismiss="alert" type="button"  &times;
    = alert

- if notice
  .alert.alert-info.alert-dismissable
    button.close aria-hidden="true" data-dismiss="alert" type="button"  &times;
    = notice

app/views/shared/_navbar.html.slim
.navbar.navbar-default role="navigation" 
  .container
    .navbar-header
      - if user_signed_in?
        button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button" 
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
      = link_to I18n.t('appname'), :root, class: 'navbar-brand'
    .navbar-collapse.collapse
      - if user_signed_in?
        ul.nav.navbar-nav
          li class=('active' if current_page? controller: 'tasks', action: 'index')
            = link_to I18n.t(:tasks_name), :root 
      ul.nav.navbar-nav.navbar-right
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
            = I18n.locale
            span.caret
          ul.dropdown-menu
            li
              = link_to :ru, url_for(locale: :ru), turbolinks: false
            li
              = link_to :en, url_for(locale: :en), turbolinks: false
        - if user_signed_in?
          li
            p.navbar-text
              = current_user.name
              | (
              = link_to t(:logout), destroy_user_session_path, method: :delete
              | )

app/views/tasks/_form.html.slim
= form_for @task do |f|
  .fields
    .form-group
      = f.label :name, t('.name')
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :description, t('.description')
      = f.text_area :description, class: 'form-control'
    .row.form-group
      .col-md-2 = f.label :start_date, t('.start_date')
      .col-md-3      
        .datetimepicker.input-group.date
          = f.text_field :start_date, :class => "form-control picker", :"data-date-format" => t('datetimepicker.format'), value: '', :def_value => @task.start_date.to_formatted_s(:iso8601), locale: I18n.locale
          span.input-group-addon
            span.glyphicon.glyphicon-calendar
      .row.form-group
      .col-md-2 = f.label :repeat_count, t('.repeat_count')
      .col-md-10 = f.number_field :repeat_count, min: 0
    .row.repeat-every
      b.col-md-2 = t('.repeat_every')
      .col-md-10
        => f.number_field :every_minutes, min: 0
        => f.label :every_minutes, t('.every_minutes')

        => f.number_field :every_hours, min: 0
        => f.label :every_hours, t('.every_hours')

        => f.number_field :every_days, min: 0
        => f.label :every_days, t('.every_days')

        => f.number_field :every_months, min: 0
        => f.label :every_months, t('.every_months')

        => f.number_field :every_years, min: 0
        => f.label :every_years, t('.every_years')
    .row
      b.col-md-2 = f.label :notify_by_sms, t('tasks.notify_by_sms')
      .col-md-10 = f.check_box :notify_by_sms
  .text-right

    => f.submit t(current_page?(action: :new) ? 'create' : 'update'), class: 'btn btn-primary'
    = link_to t('cancel'), :back, class: 'btn btn-default'

app/views/tasks/_task.html.slim
tr
  td.start_date.col-md-2 = l(task.start_date)
  td.name.col-md-6 = link_to task.name, task_path(task)
  td.actions.col-md-4
    .btn-group.pull-right
      - if task.not_performed?
        = link_to t(:mark_as_performed), mark_as_performed_task_path(task), class: 'btn btn-sm btn-primary'
        = link_to t(:edit), edit_task_path(task), class: 'btn btn-sm btn-default'
      = link_to t(:delete), task_path(task), method: :delete, class: 'btn btn-sm btn-danger'

app/views/tasks/_tasks.html.slim
.panel.panel-default
  .panel-heading = table_title
  - unless tasks.empty?
    table.tasks.table = render partial: 'task', collection: tasks
  - else
    .panel-body
      p = t(:no_found, name: t(:tasks_name))

app/views/tasks/edit.html.slim
= content_for :title
  = t '.title'
= render 'form'

app/views/tasks/index.html.slim
= content_for :title
  = t '.title'
  = link_to t('.create_new_task'), new_task_path(@task), class: 'btn btn-primary pull-right'
br
= render 'tasks', tasks: @already_need_perform, table_title: t('.need_perform') if @already_need_perform.any?
= render 'tasks', tasks: @in_future, table_title: t('.in_future') if @in_future.any?
= render 'tasks', tasks: @performed_tasks, table_title: t('.performed_tasks') if @performed_tasks.any?

app/views/tasks/new.html.slim
= content_for :title
  = t '.title'
= render 'form'

app/views/tasks/show.html.slim
.page-header
  h2.task-title
    p = @task.name
    span.label class=(@task.performed? ? 'label-success' : 'label-default') 
      = I18n.t(@task.status, scope: 'tasks.status')
    .pull-right = l @task.start_date
.container
  .row
    p = @task.description
  - if @task.repeatable?
    .row
      p 
        => t('tasks.repeating.repeat')
        = @task.repeating.downcase
  - if @task.notify_by_sms
    .row
      p = t("sms_notifications.statuses.#{@task.sms_notification.status}")
  .row
    - if @task.not_performed?
      .pull-left 
        = link_to t(:mark_as_performed), mark_as_performed_task_path(@task), class: 'btn btn-primary'
    .pull-right
      => link_to t(:back), :back, class: 'btn btn-default'
      => link_to t(:edit), edit_task_path(@task), class: 'btn btn-default' if @task.not_performed?
      = link_to t(:delete), task_path(@task), method: :delete, class: 'btn btn-danger'